# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'YouBike' do
pod 'Alamofire', '~> 3.4'
pod 'JSONWebToken'
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for YouBike
end
