# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'FIRQuickstart' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Database'
  # Pods for FIRQuickstart

end
